-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/TimeMachine/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE timemachine_title_history (
  tm_page_id INT NOT NULL,
  tm_timestamp TIMESTAMPTZ NOT NULL,
  tm_old_namespace INT NOT NULL,
  tm_old_title TEXT NOT NULL,
  tm_new_namespace INT NOT NULL,
  tm_new_title TEXT NOT NULL,
  PRIMARY KEY(tm_page_id, tm_timestamp)
);
CREATE INDEX tm_old_title_lookup ON timemachine_title_history (
  tm_old_namespace, tm_old_title, tm_timestamp
);
CREATE INDEX tm_new_title_lookup ON timemachine_title_history (
  tm_new_namespace, tm_new_title, tm_timestamp
);