-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/TimeMachine/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/timemachine_title_history (
  tm_page_id INT UNSIGNED NOT NULL,
  tm_timestamp BINARY(14) NOT NULL,
  tm_old_namespace INT NOT NULL,
  tm_old_title VARBINARY(255) NOT NULL,
  tm_new_namespace INT NOT NULL,
  tm_new_title VARBINARY(255) NOT NULL,
  INDEX tm_old_title_lookup (
    tm_old_namespace, tm_old_title, tm_timestamp
  ),
  INDEX tm_new_title_lookup (
    tm_new_namespace, tm_new_title, tm_timestamp
  ),
  PRIMARY KEY(tm_page_id, tm_timestamp)
) /*$wgDBTableOptions*/;
