-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/TimeMachine/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/timemachine_title_history (
  tm_page_id INTEGER UNSIGNED NOT NULL,
  tm_timestamp BLOB NOT NULL,
  tm_old_namespace INTEGER NOT NULL,
  tm_old_title BLOB NOT NULL,
  tm_new_namespace INTEGER NOT NULL,
  tm_new_title BLOB NOT NULL,
  PRIMARY KEY(tm_page_id, tm_timestamp)
);
CREATE INDEX tm_old_title_lookup ON /*_*/timemachine_title_history (
  tm_old_namespace, tm_old_title, tm_timestamp
);
CREATE INDEX tm_new_title_lookup ON /*_*/timemachine_title_history (
  tm_new_namespace, tm_new_title, tm_timestamp
);